spring.application.name=ss13

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:employeedb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logging Configurations
logging.level.root=INFO
logging.level.com.example.ss13.controller=DEBUG
logging.level.com.example.ss13.service=DEBUG
logging.level.com.example.ss13.aspect=DEBUG
logging.pattern.console=%d{HH:mm:ss} [%level] %logger{36} - %msg%n